---
spec/spec_helper.rb:
  ap_lib_loadpath: "$LOAD_PATH.unshift(dir, File.join(dir, 'fixtures/modules/augeasproviders_core/spec/lib'), File.join(dir, '..', 'lib'))"
  ap_load_workaround_extra: ''

.travis.yml:
  base_env: |
    # base env
      # Most tests with oldest supported ruby-augeas
      - PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
      - PUPPET=3.0.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
      - PUPPET=3.2.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
      - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
      # Test the latest ruby-augeas (~>)
      - PUPPET=3.2.0 RUBY_AUGEAS=0.5
        # Use this build to publish on the forge
      - PUPPET=3.4 RUBY_AUGEAS=0.5 FORGE_PUBLISH=true
      # Test other versions of Augeas
      - PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=0.10.0
      - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=0.10.0
      - PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0
      - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0
      - PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
      - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
      - PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.2.0
      - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.2.0
      # Issue #83: test old Augeas with new lenses
      - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0 LENSES=HEAD
      - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0 LENSES=HEAD
      - PUPPET=3.4 RUBY_AUGEAS=0.5 AUGEAS=1.0.0 LENSES=HEAD
      - PUPPET=3.4 RUBY_AUGEAS=0.5 AUGEAS=1.1.0 LENSES=HEAD
      # Test latest Puppet version
      - PUPPET=4.0 RUBY_AUGEAS=0.5
  base_exclude: |
    # base exclude
        # No support for Ruby 2.0 before Puppet 3.2.0 and ruby-augeas 0.5
        - rvm: 2.0.0
          env: PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
        - rvm: 2.0.0
          env: PUPPET=3.0.0 RUBY_AUGEAS=0.3.0
        - rvm: 2.0.0
          env: PUPPET=3.2.0 RUBY_AUGEAS=0.3.0
        - rvm: 2.0.0
          env: PUPPET=3.4 RUBY_AUGEAS=0.3.0
        - rvm: 2.0.0
          env: PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=0.10.0
        - rvm: 2.0.0
          env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=0.10.0
        - rvm: 2.0.0
          env: PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0
        - rvm: 2.0.0
          env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0
        - rvm: 2.0.0
          env: PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
        - rvm: 2.0.0
          env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
        - rvm: 2.0.0
          env: PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.2.0
        - rvm: 2.0.0
          env: PUPPET=3.0.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
        - rvm: 2.0.0
          env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.2.0
        - rvm: 2.0.0
          env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0 LENSES=HEAD
        - rvm: 2.0.0
          env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0 LENSES=HEAD
