---
spec/spec_helper.rb:
  ap_lib_loadpath: "$LOAD_PATH.unshift(dir, File.join(dir, 'fixtures/modules/augeasproviders_core/spec/lib'), File.join(dir, '..', 'lib'))"
  ap_load_workaround_extra: ''
  ap_load_core: true

.travis.yml:
  base_env: |
    # base env
      # Test latest Puppet 5 version
      - PUPPET=5.5 RUBY_AUGEAS=0.5 FORGE_PUBLISH=true
      # Test latest Puppet version
      - PUPPET=6 RUBY_AUGEAS=0.5
