language: ruby
sudo: required
rvm:
  - 2.4.4
notifications:
  email:
   - raphael.pinson@camptocamp.com
env:
<%= @configs['base_env'] %>
<%= @configs['other_env'] %>
matrix:
  fast_finish: true
<% if @configs.has_key?('base_exclude') or @configs.has_key?('other_exclude') -%>
  exclude:
<%= @configs['base_exclude'] %>
<%= @configs['other_exclude'] %>
<% end %>
install:
  - "travis_retry ./.travis.sh"
script:
  - AUGEAS_LENS_LIB=lib/augeas/lenses:augeas/lenses bundle exec rake
  # Do not include the augeas/ directory in the deployed module
  - rm -rf augeas/
deploy:
  provider: puppetforge
  user: herculesteam
  password:
    secure: "<%= @configs['forge_password'] %>"
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 2.4.4
    condition: "$FORGE_PUBLISH = true"
